---
# Run with ansible-playbook <filename> -k
#   (make sure to add the IPs of machines you want to manage to /etc/ansible/hosts first)

- name: Update Packages
  raw: (apt-get update && apt-get -y upgrade)

- name: Make sure basic packages are installed
  raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python aptitude)

- name: COMMON | Set environment
  blockinfile:
    dest: /etc/environment
    block:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
  register: newenv

- block:
  - name: COMMON | Generate locales
    raw: locale-gen en_US.UTF-8

  - name: COMMON | Reconfigure locales
    raw: update-locale LANG=en_US.UTF-8
  # only run this task block when we've just changed /etc/environment
  when: newenv.changed
